### ISSUE TITLE
Why the VMOT pours under the chip? 

### ISSUE THREAD

**Issue by Duckle29** [hzeller/quadrigotion#3]
Hey there. I was wondering why VMOT had rectangular pours under the chip 

![image](https://user-images.githubusercontent.com/2756925/36951013-abe0f93a-1ffe-11e8-871c-6f381f9b57a6.png)

It's not present in the example layout from trinamic, and I can't seem to find any info on the pins being use for cooling.

**Comment by hzeller** [comment]
Yes, this is meant as part of the cooling with the vias bolting together top and bottom transferring heat. More copper, even inner copper helps.
The cooling requirements are described in 14.3 in the TMC2660 datasheet and also shown a little in the 14.5 sample layout (though they don't do a good job there)

**Comment by Duckle29** [comment]
Okay good to hear, and thanks for the pointer to the section that mentions it :)
