### ISSUE TITLE
Step stick format?

### ISSUE THREAD

**Issue by boelle** [hzeller/quadrigotion#4]
Do you have any plans to make a step stick format of the board?

of course only a single chip can fit on the board

just a thought, been using google to see if it has been done and your board is what comes close

**Comment by rafaljot** [comment]
no way to place tmc2660 in step stick format. Maybe vertically.
Panucatt made"Bigfoot"
https://www.panucatt.com/azteeg_X5_GT_reprap_3d_printer_controller_p/ax5gt.htm

**Comment by boelle** [comment]
bigfoot is not a stepper driver

all their stepper drivers are here: http://www.panucatt.com/category_s/1832.htm

sadly no 2660

**Comment by rafaljot** [comment]
Yes, it is.
"The BSD109A is a bi-polar stepper driver board using the **new Bigfoot profile which is twice the size of the regular pololu style drivers** used in 3D printers and CNCs. The BSD109A is controlled using Step and Direction signals from a micro controller. "
http://www.panucatt.com/product_p/bsd109a.htm

2660 
https://www.kreativ-fraesen.de/technisches/3d-drucker/stepper-driver-tmc2660-en/
http://panucattdevices.freshdesk.com/support/solutions/articles/1000227573-bigfoot-bsd2660

you can chose them here (3pc Bigfoot 2660 SPI , add $36)
https://www.panucatt.com/azteeg_X5_GT_reprap_3d_printer_controller_p/ax5gt.htm

**Comment by snmcma** [comment]
Is there an error in the board on the j400 element? both pins are connected together

**Comment by hzeller** [comment]
It is intentional, this is a jumper, usually to be just bridged with a 0 ohm resistor; For symmetry, it is on all four parts of the circuit, but usually the last in the chain needs to be bridged. To avoid having to do that, it is connected already by default.

(You only need jumpers if you do not want to populate all chips)
